In [70]:
%run 'C:\dev\prod\metrikaHelper.py'
import pandas as pd
import psycopg2
import math
import numpy
from datetime import timedelta
from datetime import datetime
from pandas import ExcelWriter
def getVipProjectByDomain(domain):
    conn = psycopg2.connect("dbname='CRM' user='read_only' host='192.168.10.10' password='User_ro'")
    cur = conn.cursor()
    cur.execute("SELECT p.projectid, p.domain, p2.login, p2.password FROM project AS p INNER JOIN ProjectMetrikaData AS p2 ON p.UniqueId = p2.ProjectUniqueId WHERE domain=%s ORDER BY p.projectid", [domain])
    result = []
    rows = cur.fetchall()
    for row in rows:
        result.append(getVipProjectByRow(row))
    return result
def getVipProjectByRow(row):
    return {'projectid': row[0], 'domain': row[1], 'metrikalogin': row[2], 'metrikapassword': row[3]}
def getCPATargetsByProjectID(projectID):
    conn = psycopg2.connect("dbname='Cubo' user='read_only' host='192.168.10.8' password='User_ro'")
    cur = conn.cursor()
    cur.execute("SELECT targetstatus, targetid, targetname FROM metricstarget WHERE projectid=%s ORDER BY id DESC", [projectID])
    result = []
    rows = cur.fetchall()
    for row in rows:
        result.append(getCPATargetByRow(row))
    return result
def getCPATargetByRow(row):
    return {'targetstatus': row[0], 'targetid': row[1], 'targetname': row[2]}
def getDirectCallByProjectID(projectID,date1,date2):
    conn = psycopg2.connect("dbname='CuboHistory' user='read_only' host='192.168.10.32' password='User_ro'")
    cur = conn.cursor()
    cur.execute("SELECT id, duration, phonenumbera, date FROM calltrackinginfo where projectid={0} and campaign='direct' and date >= '{1}' and date <= '{2}'".format(projectID,date1,date2))
    result = []
    rows = cur.fetchall()
    for row in rows:
        result.append(getCallByRow(row))
    return result
def getCallByRow(row):
    return {'id': row[0], 'duration': row[1], 'phonenumbera': row[2], 'date':row[3]}

Получаем данные проекта

In [71]:
project = u'restorate.ru'
VipProjectInfo = getVipProjectByDomain(project)
print VipProjectInfo
metrikaCredentials = getMetrikaCredentialsByLPD({'yandexLogin':VipProjectInfo[0]['metrikalogin'],
                                                 'yandexPassword':VipProjectInfo[0]['metrikapassword'],
                                                 'domain':VipProjectInfo[0]['domain']})
print metrikaCredentials

[{'metrikalogin': 'RookeeXML@yandex.ru', 'projectid': 2406006L, 'domain': 'restorate.ru', 'metrikapassword': 'pass-RookeeXML'}]
{'Token': u'71e4f97915d34895b4de3b45dbb6beef', 'counterID': [23008126]}

Получаем данные из Яндекс.Метрики

In [91]:
goalsMetrics = ','.join(['ym:s:goal'+str(target['targetid'])+'visits' for target in getCPATargetsByProjectID(VipProjectInfo[0]['projectid'])])
otherMetrics = 'ym:s:visits'
metrics = ','.join([otherMetrics,goalsMetrics])
dimensions='ym:s:dateTime'
date1 = '2016-01-01'
date2 = '2016-03-21'
token = metrikaCredentials['Token']
counterId = metrikaCredentials['counterID'][0]
params = '&'.join(['dimensions={0}'.format(dimensions),
                   'metrics={0}'.format(metrics),
                   'date1={0}'.format(date1),
                  'date2={0}'.format(date2),
                  'ids={0}'.format(counterId),
                  'oauth_token={0}'.format(token),
                  'limit=10000',
                  'offset=1',
                  "filters=ym:s:UTMMedium=='direct'"])
url = 'https://beta.api-metrika.yandex.ru/stat/v1/data.csv?'+params
print url
df = pd.read_csv(url,encoding='utf-8')
total_visits = int(df[df[u'﻿"Дата и время визита"'] == u'Итого и средние'][u'Визиты'])
current_visits = int(df[df[u'﻿"Дата и время визита"'] != u'Итого и средние'][u'Визиты'].sum())
if current_visits < total_visits:
    offset = 10001
    while current_visits < total_visits:
        params = '&'.join(['dimensions={0}'.format(dimensions),
                   'metrics={0}'.format(metrics),
                   'date1={0}'.format(date1),
                  'date2={0}'.format(date2),
                  'ids={0}'.format(counterId),
                  'oauth_token={0}'.format(token),
                  'limit=10000',
                  'offset={0}'.format(offset),
                  "filters=ym:s:UTMMedium=='direct'"])
        url = 'https://beta.api-metrika.yandex.ru/stat/v1/data.csv?'+params
        extra_df = pd.read_csv(url,encoding='utf-8')
        total_df = pd.concat([df,extra_df])
        df = total_df.reset_index(drop=True)
        current_visits = int(df[df[u'﻿"Дата и время визита"'] != u'Итого и средние'][u'Визиты'].sum())
        offset += 10000
print len(df)
if len(df) < 500:
    print 'Not enough data'
else:
    df.rename(columns={u'﻿"Дата и время визита"': 'datetime',
                        u'Визиты': 'visits'
                       }, inplace=True)
    for i in xrange(0,len(df)):
        df.loc[i,'sumCPAVisits'] = df.loc[i,[column for column in df.columns if u'Целевые визиты' in column]].sum()
    df['domain'] = VipProjectInfo[0]['domain']
    df = df[~df[u'datetime'].isin([u'Итого и средние'])]
    cpaVisitsCount = df['sumCPAVisits'].sum()
print cpaVisitsCount

https://beta.api-metrika.yandex.ru/stat/v1/data.csv?dimensions=ym:s:dateTime&metrics=ym:s:visits,ym:s:goal16355695visits&date1=2016-01-01&date2=2016-03-21&ids=23008126&oauth_token=71e4f97915d34895b4de3b45dbb6beef&limit=10000&offset=1&filters=ym:s:UTMMedium=='direct'
4018
151.0

In [93]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['hours'] = df['datetime'].dt.hour
df['dayofweek'] = df['datetime'].dt.weekday

Пример создания сводных таблиц и запись на один Excel-лист

In [117]:
def createPivot(df,sumValue):
    return pd.pivot_table(df, values=sumValue, index=['dayofweek'], columns=['hours'], aggfunc=sum)
def divideDataframes(df2,df1):
    return pd.DataFrame(df2.values/df1.values, columns=df1.columns, index=df1.index)

In [350]:
pivotVisitsDataframe = createPivot(df,'visits')
pivotCPAVisitsDataframe = createPivot(df,'sumCPAVisits')
conversionDataframe = divideDataframes(pivotCPAVisitsDataframe,pivotVisitsDataframe)

In [125]:
writer = ExcelWriter('D:\\output1.xlsx')
pivotVisitsDataframe.to_excel(writer, sheet_name='Sheet1', startrow=0 , startcol=0)
pivotCPAVisitsDataframe.to_excel(writer, sheet_name='Sheet1', startrow=9 , startcol=0)
conversionDataframe.to_excel(writer, sheet_name='Sheet1', startrow=18 , startcol=0)
writer.save()

Пример записи в Excel со скользящим окном

In [247]:
last_date = datetime(2016, 2, 26)
numDays = 12
window_size = 7
date_list = [last_date - timedelta(days=x) for x in range(0, numDays)]
writer = ExcelWriter('D:\\output1.xlsx')
for endDate in date_list:
    startDate = endDate - timedelta(days=window_size)
    df1 = df.loc[(df['datetime'] >= startDate) & (df['datetime'] <= endDate)]
    print startDate.strftime('%Y-%m-%d'),endDate.strftime('%Y-%m-%d'),df1['visits'].sum()
    sheetName = '{0} {1}'.format(startDate.strftime('%Y-%m-%d'),endDate.strftime('%Y-%m-%d'))
    pivotVisitsDataframe = createPivot(df1,'visits')
    pivotCPAVisitsDataframe = createPivot(df1,'sumCPAVisits')
    conversionDataframe = divideDataframes(pivotCPAVisitsDataframe,pivotVisitsDataframe)
    pivotVisitsDataframe.to_excel(writer, sheet_name=sheetName, startrow=0 , startcol=0)
    pivotCPAVisitsDataframe.to_excel(writer, sheet_name=sheetName, startrow=9 , startcol=0)
    conversionDataframe.to_excel(writer, sheet_name=sheetName, startrow=18 , startcol=0)
writer.save()

2016-02-19 2016-02-26 1555.0
2016-02-18 2016-02-25 1249.0
2016-02-17 2016-02-24 1120.0
2016-02-16 2016-02-23 1068.0
2016-02-15 2016-02-22 1000.0
2016-02-14 2016-02-21 968.0
2016-02-13 2016-02-20 922.0
2016-02-12 2016-02-19 988.0
2016-02-11 2016-02-18 1064.0
2016-02-10 2016-02-17 1006.0
2016-02-09 2016-02-16 1018.0
2016-02-08 2016-02-15 1073.0

Пример применения действий к ячейкам

In [249]:
pivotVisitsDataframe.fillna(0,inplace=True)
pivotCPAVisitsDataframe.fillna(0,inplace=True)
conversionDataframe.fillna(0,inplace=True)
DecisionDataframe = pivotCPAVisitsDataframe
for i in DecisionDataframe.index:
    for j in DecisionDataframe.columns:
        if pivotVisitsDataframe.loc[i,j] > pivotVisitsDataframe.loc[i,].mean() and pivotCPAVisitsDataframe.loc[i,j] > pivotCPAVisitsDataframe.loc[i,].mean():
            DecisionDataframe.loc[i,j] = min(2.0,1+conversionDataframe.loc[i,j]/conversionDataframe.loc[0,][conversionDataframe.loc[0,] <> 0].mean())
        elif pivotVisitsDataframe.loc[i,j] > pivotVisitsDataframe.loc[i,].mean() and pivotCPAVisitsDataframe.loc[i,j] == 0:
            DecisionDataframe.loc[i,j] = pivotVisitsDataframe.loc[i,].mean()/pivotVisitsDataframe.loc[i,j]
        else:
            DecisionDataframe.loc[i,j] = 1

Функция для расчета корректировок ставок на основе z-критерия

In [73]:
def calculate_bid_adjustments_for_dateframe(df,start_date,end_date):
    hour_dayweek_dataframe = df.loc[(df['datetime'] >= start_date) & (df['datetime'] <= end_date)][['datetime','visits','sumCPAVisits','hours','dayofweek']].groupby(by=['hours','dayofweek'],as_index=False).sum()
    hour_dayweek_dataframe['conversion_rate'] = hour_dayweek_dataframe['sumCPAVisits']/hour_dayweek_dataframe['visits']
    conversion_rate_std = hour_dayweek_dataframe['conversion_rate'].std()
    total_conversion_rate = hour_dayweek_dataframe['sumCPAVisits'].sum()/hour_dayweek_dataframe['visits'].sum()
    hour_dayweek_dataframe['sqrt_visits'] = hour_dayweek_dataframe['visits'].apply(numpy.sqrt)
    hour_dayweek_dataframe['z_criteria'] = (hour_dayweek_dataframe['conversion_rate'] - total_conversion_rate)/(conversion_rate_std/hour_dayweek_dataframe['sqrt_visits'])
    maximum_z_criteria = hour_dayweek_dataframe['z_criteria'].max()
    minimum_z_criteria = hour_dayweek_dataframe['z_criteria'].min()
    delta_z_criteria = maximum_z_criteria - minimum_z_criteria
    max_bid_adjustment = 2
    min_bid_adjustment = 0.5
    adjustment_step = (max_bid_adjustment-min_bid_adjustment)/delta_z_criteria
    hour_dayweek_dataframe['bid_adjustment'] = (hour_dayweek_dataframe['z_criteria'] + abs(minimum_z_criteria))*adjustment_step + min_bid_adjustment
    hour_dayweek_dataframe['new_visits'] =  hour_dayweek_dataframe['visits']*hour_dayweek_dataframe['bid_adjustment']
    hour_dayweek_dataframe['new_cost'] = hour_dayweek_dataframe['new_visits']*hour_dayweek_dataframe['bid_adjustment']
    hour_dayweek_dataframe['new_cpa_visits'] = hour_dayweek_dataframe['conversion_rate']*hour_dayweek_dataframe['new_visits']
    return hour_dayweek_dataframe

In [300]:
aggregate_df = pd.DataFrame()
last_date = datetime(2016, 2, 26)
numDays = 12
window_size = 7
date_list = [last_date - timedelta(days=x) for x in range(0, numDays)]
for endDate in date_list:
    print startDate.strftime('%Y-%m-%d'),endDate.strftime('%Y-%m-%d')
    startDate = endDate - timedelta(days=window_size)
    df1 = calculate_bid_adjustments_for_dateframe(df,startDate,endDate)
    df1['period'] = '{0} {1}'.format(startDate.strftime('%Y-%m-%d'),endDate.strftime('%Y-%m-%d'))
    aggregate_df = pd.concat([aggregate_df,df1])

2016-02-08 2016-02-26
2016-02-19 2016-02-25
2016-02-18 2016-02-24
2016-02-17 2016-02-23
2016-02-16 2016-02-22
2016-02-15 2016-02-21
2016-02-14 2016-02-20
2016-02-13 2016-02-19
2016-02-12 2016-02-18
2016-02-11 2016-02-17
2016-02-10 2016-02-16
2016-02-09 2016-02-15

Критерий достаточности статистических данных

In [352]:
float(numpy.sum(abs(total_df['z_criteria']) > 1.96))/float(numpy.sum(abs(total_df['z_criteria']) > 0)) > 0.75

True

Моделирование с учетом критерия достаточности статистических данных

In [21]:
data_significant_criteria = 0.75
aggregate_df = pd.DataFrame()
last_date = datetime(2016, 3, 21)
numDays = 12
date_list = [last_date - timedelta(days=x) for x in range(0, numDays)]
for endDate in date_list:
    window_size = 7
    startDate = endDate - timedelta(days=window_size)
    print startDate.strftime('%Y-%m-%d'),endDate.strftime('%Y-%m-%d')
    is_enough_data = False
    i = 0
    while not is_enough_data:
        i += 1
        startDate = endDate - timedelta(days=window_size)
        df1 = calculate_bid_adjustments_for_dateframe(df,startDate,endDate)
        try:
            is_enough_data = float(numpy.sum(abs(df1['z_criteria']) > 1.96))/float(numpy.sum(abs(df1['z_criteria']) > 0)) > data_significant_criteria
        except ZeroDivisionError:
            print 'zero division error'
            break
        window_size += 1
        if i > 30:
            print 'not enough data for analysis'
            break
    df1['start_date'] = startDate.strftime('%Y-%m-%d')
    df1['end_date'] = endDate.strftime('%Y-%m-%d')
    aggregate_df = pd.concat([aggregate_df,df1])

2016-03-14 2016-03-21
2016-03-13 2016-03-20
2016-03-12 2016-03-19
2016-03-11 2016-03-18
2016-03-10 2016-03-17
2016-03-09 2016-03-16
2016-03-08 2016-03-15
2016-03-07 2016-03-14
2016-03-06 2016-03-13
2016-03-05 2016-03-12
not enough data for analysis
2016-03-04 2016-03-11
not enough data for analysis
2016-03-03 2016-03-10
not enough data for analysis

In [22]:
aggregate_df.to_excel('D:\\output3.xls')

In [386]:
total_df = calculate_bid_adjustments_for_dateframe(df,'2016-02-14','2016-03-16')

In [387]:
total_df

,hours,dayofweek,visits,sumCPAVisits,conversion_rate,sqrt_visits,z_criteria,bid_adjustment
0,0,0,8,0,0.000000,2.828427,-2.359744,0.767530
1,0,1,11,0,0.000000,3.316625,-2.767045,0.741645
2,0,5,5,0,0.000000,2.236068,-1.865541,0.798939
3,0,6,18,1,0.055556,4.242641,4.976126,1.233753
4,1,0,4,0,0.000000,2.000000,-1.668591,0.811455
5,1,1,3,0,0.000000,1.732051,-1.445042,0.825663
6,1,5,4,0,0.000000,2.000000,-1.668591,0.811455
7,1,6,4,0,0.000000,2.000000,-1.668591,0.811455
8,2,0,2,0,0.000000,1.414214,-1.179872,0.842515
9,2,5,3,0,0.000000,1.732051,-1.445042,0.825663
10,2,6,2,0,0.000000,1.414214,-1.179872,0.842515
11,3,0,2,0,0.000000,1.414214,-1.179872,0.842515
12,3,1,1,0,0.000000,1.000000,-0.834295,0.864478
13,3,5,3,0,0.000000,1.732051,-1.445042,0.825663
14,3,6,1,0,0.000000,1.000000,-0.834295,0.864478
15,4,0,1,0,0.000000,1.000000,-0.834295,0.864478
16,4,1,2,0,0.000000,1.414214,-1.179872,0.842515
17,4,5,1,0,0.000000,1.000000,-0.834295,0.864478
18,4,6,2,0,0.000000,1.414214,-1.179872,0.842515
19,5,0,1,0,0.000000,1.000000,-0.834295,0.864478
20,5,1,2,0,0.000000,1.414214,-1.179872,0.842515
21,5,5,2,0,0.000000,1.414214,-1.179872,0.842515
22,6,0,2,0,0.000000,1.414214,-1.179872,0.842515
23,6,1,2,0,0.000000,1.414214,-1.179872,0.842515
24,6,2,1,0,0.000000,1.000000,-0.834295,0.864478
25,6,6,1,0,0.000000,1.000000,-0.834295,0.864478
26,7,0,6,0,0.000000,2.449490,-2.043598,0.787622
27,7,1,9,0,0.000000,3.000000,-2.502886,0.758433
28,7,5,5,0,0.000000,2.236068,-1.865541,0.798939
29,7,6,4,0,0.000000,2.000000,-1.668591,0.811455
...,...,...,...,...,...,...,...,...
91,18,5,26,1,0.038462,5.099020,2.831437,1.097449
92,18,6,22,1,0.045455,4.690416,3.789586,1.158343
93,19,0,37,2,0.054054,6.082763,6.804398,1.349946
94,19,1,37,0,0.000000,6.082763,-5.074821,0.594977
95,19,4,18,1,0.055556,4.242641,4.976126,1.233753
96,19,5,30,0,0.000000,5.477226,-4.569624,0.627084
97,19,6,25,2,0.080000,5.000000,10.280216,1.570848
98,20,0,40,1,0.025000,6.324555,0.435986,0.945209
99,20,1,10,0,0.000000,3.162278,-2.638274,0.749828
100,20,4,19,0,0.000000,4.358899,-3.636609,0.686380
101,20,5,27,2,0.074074,5.196152,9.571022,1.525776
102,20,6,39,1,0.025641,6.244998,0.575134,0.954053
103,21,0,5,0,0.000000,2.236068,-1.865541,0.798939
104,21,1,4,0,0.000000,2.000000,-1.668591,0.811455
105,21,2,1,0,0.000000,1.000000,-0.834295,0.864478
106,21,4,20,0,0.000000,4.472136,-3.731083,0.680376
107,21,5,16,0,0.000000,4.000000,-3.337182,0.705410
108,21,6,22,0,0.000000,4.690416,-3.913192,0.668802
109,22,0,3,0,0.000000,1.732051,-1.445042,0.825663
110,22,1,3,0,0.000000,1.732051,-1.445042,0.825663
111,22,4,31,0,0.000000,5.567764,-4.645160,0.622283
112,22,5,22,0,0.000000,4.690416,-3.913192,0.668802
113,22,6,28,0,0.000000,5.291503,-4.414676,0.636931
114,23,0,1,0,0.000000,1.000000,-0.834295,0.864478
115,23,1,2,0,0.000000,1.414214,-1.179872,0.842515
116,23,2,1,0,0.000000,1.000000,-0.834295,0.864478
117,23,3,1,0,0.000000,1.000000,-0.834295,0.864478
118,23,4,13,2,0.153846,3.605551,17.032798,2.000000
119,23,5,15,0,0.000000,3.872983,-3.231212,0.712145
120,23,6,8,0,0.000000,2.828427,-2.359744,0.767530

In [388]:
float(numpy.sum(abs(total_df['z_criteria']) > 1.96))/float(numpy.sum(abs(total_df['z_criteria']) > 0))

0.49586776859504134

In [390]:
float(numpy.sum(abs(df1['z_criteria']) > 0))

0.0

In [399]:
df1

,hours,dayofweek,visits,sumCPAVisits,conversion_rate,sqrt_visits,z_criteria,bid_adjustment,start_date,end_date
0,8,2,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
1,9,3,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
2,9,4,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
3,9,5,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
4,10,2,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
5,11,5,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
6,12,4,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
7,15,0,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
8,15,3,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
9,16,3,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
10,16,6,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
11,17,0,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
12,19,4,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
13,20,5,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
14,23,2,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05
15,23,3,1,0,0,1,NaN,NaN,2016-02-27,2016-03-05

In [400]:
df.loc[(df['datetime'] >= '2016-02-28') & (df['datetime'] <= '2016-03-05')]

,datetime,visits,Целевые визиты,sumCPAVisits,domain,hours,dayofweek
34654,2016-02-28 16:25:10,1,0,0,samson-pharma.ru,16,6
34655,2016-02-29 15:03:50,1,0,0,samson-pharma.ru,15,0
34656,2016-02-29 17:46:38,1,0,0,samson-pharma.ru,17,0
34657,2016-03-02 08:45:29,1,0,0,samson-pharma.ru,8,2
34658,2016-03-02 10:50:14,1,0,0,samson-pharma.ru,10,2
34659,2016-03-02 23:23:31,1,0,0,samson-pharma.ru,23,2
34660,2016-03-03 09:02:12,1,0,0,samson-pharma.ru,9,3
34661,2016-03-03 15:45:41,1,0,0,samson-pharma.ru,15,3
34662,2016-03-03 16:54:08,1,0,0,samson-pharma.ru,16,3
34663,2016-03-03 23:12:36,1,0,0,samson-pharma.ru,23,3
34664,2016-03-04 09:37:01,1,0,0,samson-pharma.ru,9,4
34665,2016-03-04 12:37:04,1,0,0,samson-pharma.ru,12,4
34666,2016-03-04 19:53:45,1,0,0,samson-pharma.ru,19,4

In [110]:
def calculate_bid_adjustments_for_dateframe(df,start_date,end_date):
    hour_dayweek_dataframe = df.loc[(df['datetime'] >= start_date) & (df['datetime'] <= end_date)][['datetime','visits','sumCPAVisits','hours','dayofweek']].groupby(by=['hours','dayofweek'],as_index=False).sum()
    hour_dayweek_dataframe['conversion_rate'] = hour_dayweek_dataframe['sumCPAVisits']/hour_dayweek_dataframe['visits']
    conversion_rate_std = hour_dayweek_dataframe['conversion_rate'].std()
    total_conversion_rate = hour_dayweek_dataframe['sumCPAVisits'].sum()/hour_dayweek_dataframe['visits'].sum()
    hour_dayweek_dataframe['sqrt_visits'] = hour_dayweek_dataframe['visits'].apply(numpy.sqrt)
    hour_dayweek_dataframe['z_criteria'] = (hour_dayweek_dataframe['conversion_rate'] - total_conversion_rate)/(conversion_rate_std/hour_dayweek_dataframe['sqrt_visits'])
    maximum_z_criteria = hour_dayweek_dataframe['z_criteria'].max()
    minimum_z_criteria = hour_dayweek_dataframe['z_criteria'].min()
    delta_z_criteria = maximum_z_criteria - minimum_z_criteria
    max_bid_adjustment = 2
    min_bid_adjustment = 0.6
    adjustment_step = (max_bid_adjustment-min_bid_adjustment)/delta_z_criteria
    hour_dayweek_dataframe['bid_adjustment'] = (hour_dayweek_dataframe['z_criteria'] + abs(minimum_z_criteria))*adjustment_step + min_bid_adjustment
    hour_dayweek_dataframe['new_visits'] =  hour_dayweek_dataframe['visits']*hour_dayweek_dataframe['bid_adjustment']
    hour_dayweek_dataframe['new_cost'] = hour_dayweek_dataframe['new_visits']*hour_dayweek_dataframe['bid_adjustment']
    hour_dayweek_dataframe['new_cpa_visits'] = hour_dayweek_dataframe['conversion_rate']*hour_dayweek_dataframe['new_visits']
    return hour_dayweek_dataframe

In [111]:
hdf = calculate_bid_adjustments_for_dateframe(df,'2016-01-01','2016-03-21')

In [113]:
hdf.to_clipboard()

In [102]:
float(numpy.sum(abs(hdf['z_criteria']) > 1.96))/float(numpy.sum(abs(hdf['z_criteria']) > 0))

0.6706586826347305

In [112]:
print 'old visits:',hdf['visits'].sum()
print 'old cost:',hdf['visits'].sum()
print 'old cpa_visits:',hdf['sumCPAVisits'].sum()
print 'old cpa:',hdf['visits'].sum()/hdf['sumCPAVisits'].sum()
print 'old conversion rate (%):',hdf['sumCPAVisits'].sum()/hdf['visits'].sum()*100
print ' '
print 'new visits:',hdf['new_visits'].sum()
print 'new cost:',hdf['new_cost'].sum()
print 'new cpa_visits:',hdf['new_cpa_visits'].sum()
print 'new cpa:',hdf['new_cost'].sum()/hdf['new_cpa_visits'].sum()
print 'new conversion rate (%):',hdf['new_cpa_visits'].sum()/hdf['new_visits'].sum()*100

old visits: 3961.0
old cost: 3961.0
old cpa_visits: 151.0
old cpa: 26.2317880795
old conversion rate (%): 3.81216864428

new visits: 3810.71005764
new cost: 4034.02013863
new cpa_visits: 195.056466826
new cpa: 20.6812940082
new conversion rate (%): 5.11863836071

In [59]:
hdf.to_excel('D:\\timebidexp.xlsx')

In [69]:
calls_df = pd.DataFrame(getDirectCallByProjectID(2406006,'2016-02-15','2016-03-21'))
calls_df = calls_df[calls_df['duration'] > 1]

KeyError: 'duration'

In [57]:
calls_df['date'] = pd.to_datetime(calls_df['date'])
calls_df['hours'] = calls_df['date'].dt.hour
calls_df['dayofweek'] = calls_df['date'].dt.weekday

In [58]:
unique_calls_df = calls_df.drop_duplicates(subset=['phonenumbera'])

In [34]:
calls_hdf = unique_calls_df.groupby(by=['hours','dayofweek'],as_index=False).count()[['hours','dayofweek','id']].rename(columns={'id': 'calls'})

In [33]:
unique_calls_df.to_clipboard()

In [37]:
calls_hdf.to_clipboard()

In [43]:
result_df = pd.merge(hdf,calls_hdf,how='outer',on=['hours','dayofweek']).fillna(0)

In [44]:
result_df.to_clipboard()

In [60]:
def calculate_bid_adjustments_with_calls(metrika_df,calls_df,start_date,end_date):
    hour_dayweek_dataframe = metrika_df.loc[(metrika_df['datetime'] >= start_date) & (metrika_df['datetime'] <= end_date)][['datetime','visits','sumCPAVisits','hours','dayofweek']].groupby(by=['hours','dayofweek'],as_index=False).sum()
    calls_hdf = calls_df.loc[(calls_df['date'] >= start_date) & (calls_df['date'] <= end_date)].groupby(by=['hours','dayofweek'],as_index=False).count()[['hours','dayofweek','id']].rename(columns={'id': 'calls'})
    hour_dayweek_dataframe = pd.merge(hour_dayweek_dataframe,calls_hdf,how='outer',on=['hours','dayofweek']).fillna(0)
    hour_dayweek_dataframe['allGoalVisits'] = hour_dayweek_dataframe['sumCPAVisits']+hour_dayweek_dataframe['calls']
    hour_dayweek_dataframe['conversion_rate'] = hour_dayweek_dataframe['allGoalVisits']/hour_dayweek_dataframe['visits']
    conversion_rate_std = hour_dayweek_dataframe['conversion_rate'].std()
    total_conversion_rate = hour_dayweek_dataframe['allGoalVisits'].sum()/hour_dayweek_dataframe['visits'].sum()
    hour_dayweek_dataframe['sqrt_visits'] = hour_dayweek_dataframe['visits'].apply(numpy.sqrt)
    hour_dayweek_dataframe['z_criteria'] = (hour_dayweek_dataframe['conversion_rate'] - total_conversion_rate)/(conversion_rate_std/hour_dayweek_dataframe['sqrt_visits'])
    maximum_z_criteria = hour_dayweek_dataframe['z_criteria'].max()
    minimum_z_criteria = hour_dayweek_dataframe['z_criteria'].min()
    delta_z_criteria = maximum_z_criteria - minimum_z_criteria
    max_bid_adjustment = 2
    min_bid_adjustment = 0.7
    adjustment_step = (max_bid_adjustment-min_bid_adjustment)/delta_z_criteria
    hour_dayweek_dataframe['bid_adjustment'] = (hour_dayweek_dataframe['z_criteria'] + abs(minimum_z_criteria))*adjustment_step + min_bid_adjustment
    hour_dayweek_dataframe['new_visits'] =  hour_dayweek_dataframe['visits']*hour_dayweek_dataframe['bid_adjustment']
    hour_dayweek_dataframe['new_cost'] = hour_dayweek_dataframe['new_visits']*hour_dayweek_dataframe['bid_adjustment']
    hour_dayweek_dataframe['new_cpa_visits'] = hour_dayweek_dataframe['conversion_rate']*hour_dayweek_dataframe['new_visits']
    return hour_dayweek_dataframe

In [61]:
calculate_bid_adjustments_with_calls(df,unique_calls_df,'2016-02-15','2016-03-21').to_clipboard()

In [68]:
calls_df

                   date  duration      id phonenumbera  hours  dayofweek
0   2016-02-15 05:44:52         6  127779  74232465846      5          0
1   2016-02-15 08:54:20         3  127780  79924067849      8          0
2   2016-02-15 11:39:48         8  127781  79269649356     11          0
3   2016-02-15 11:40:08        32  127782  79269649356     11          0
4   2016-02-15 11:57:09        58  127783  79773559599     11          0
5   2016-02-15 11:58:42        11  127784  79773559599     11          0
6   2016-02-15 11:59:05       360  127785  79773559599     11          0
7   2016-02-15 17:08:56        35  127786  79853136633     17          0
8   2016-02-16 10:44:11       160  128372  79652112372     10          1
9   2016-02-16 13:08:10       504  128373  79150609989     13          1
10  2016-02-16 15:03:38       124  128374  74953038241     15          1
11  2016-02-16 17:54:26        21  128375  79031364536     17          1
12  2016-02-20 15:23:35        79  129666  79251033032     15          5
13  2016-02-17 11:48:21         5  128723  79850044715     11          2
14  2016-02-17 11:48:42        41  128724  79850044715     11          2
15  2016-02-17 12:07:45        87  128725  79157110123     12          2
16  2016-02-18 06:18:01        88  128934  73494922924      6          3
17  2016-02-18 11:48:00        84  128935  78672516335     11          3
18  2016-02-18 12:17:49       360  128936  79377363696     12          3
19  2016-02-18 13:07:39       158  128937  73832295847     13          3
20  2016-02-18 16:36:23       168  128938  79652424334     16          3
21  2016-02-18 17:17:53        47  128939  78793976091     17          3
23  2016-02-19 11:48:00        63  129314  79015472510     11          4
24  2016-02-19 17:05:55        19  129315  79154377437     17          4
25  2016-02-19 17:06:58        68  129316  79154377437     17          4
27  2016-02-19 19:24:49        78  129318  79262350435     19          4
28  2016-02-20 10:03:16       470  129655  73422445105     10          5
29  2016-02-20 11:10:40        39  129656  79911182395     11          5
30  2016-02-20 12:25:23         6  129657  79051525115     12          5
31  2016-02-20 12:26:05       130  129658  79051525115     12          5
..                  ...       ...     ...          ...    ...        ...
81  2016-03-09 15:19:40        43  134412  79878908560     15          2
82  2016-03-09 15:32:42        66  134413  74954191535     15          2
83  2016-03-09 16:56:16        72  134414  79686512980     16          2
85  2016-03-10 08:56:56        81  134682  79657185376      8          3
86  2016-03-10 08:58:58       130  134683  79657185376      8          3
87  2016-03-10 10:54:17        51  134684  74955892747     10          3
88  2016-03-10 11:12:26        66  134685  79629235173     11          3
89  2016-03-10 14:28:15       103  134686  79646216030     14          3
90  2016-03-10 17:37:10        33  134687  79037993679     17          3
92  2016-03-11 13:18:52        46  135151  73452225472     13          4
93  2016-03-14 13:35:33       118  135967  73452201059     13          0
94  2016-03-14 14:54:58       281  135968  79067885468     14          0
95  2016-03-14 16:31:15       115  135969  79296016485     16          0
96  2016-03-14 16:53:02        46  135970  79211583563     16          0
97  2016-03-15 13:48:36        45  136402  79033216810     13          1
98  2016-03-16 12:36:39       389  136750  74952048707     12          2
99  2016-03-16 13:59:59       116  136751  79605385500     13          2
100 2016-03-16 14:57:09        65  136752  79030093188     14          2
101 2016-03-16 16:27:09       115  136753  74954800479     16          2
102 2016-03-17 09:06:13       268  136950  79267213115      9          3
103 2016-03-17 11:01:56       286  136951  79127197350     11          3
104 2016-03-17 11:53:10      1407  136952  79175133629     11          3
105 2016-03-17 13:47:28       141  136953  79166786956     13          3
106 2016-03-17 13:55:16       180  136954  79101802199     13          3
107 2016-03-17 14:26:25       273  136955  79261249177     14          3
108 2016-03-17 17:16:26        68  136956  79651387744     17          3
109 2016-03-17 17:18:20        56  136957  79651387744     17          3
110 2016-03-18 13:28:27        68  137420  74993720515     13          4
111 2016-03-18 13:38:45       523  137421  74959891598     13          4
112 2016-03-18 14:38:13        45  137422  79853433448     14          4

[105 rows x 6 columns]

In [119]:
import math

def myround(x, base=10):
    return int(base * round(float(x)/base))
list_of_dictionaries = [hdf.iloc[line,:].T.to_dict() for line in range(len(hdf))]

In [126]:
schedule = []
for item in list_of_dictionaries:
    scheduleItem = {}
    print item['bid_adjustment']
    item['rnd_bid_adjustment'] = myround(item['bid_adjustment']*100)
    print item['rnd_bid_adjustment']
    scheduleItem['hour'] = int(item['hours'])
    scheduleItem['day'] = int(item['dayofweek'])
    scheduleItem['value'] = item['rnd_bid_adjustment']
    schedule.append(scheduleItem)

0.951241989787
100
0.639811028097
60
0.714273320129
70
0.754303104057
80
0.733399971173
70
0.921642876107
90
0.951241989787
100
1.0656682518
110
0.7204786399
70
0.769512992547
80
1.11826384324
110
1.33559166948
130
0.754303104057
80
1.0656682518
110
0.786052762811
80
0.777594633388
80
0.777594633388
80
0.786052762811
80
1.18447949412
120
0.740146085033
70
0.726849522068
70
0.814358094477
80
0.864428329691
90
0.849744875934
80
0.786052762811
80
0.814358094477
80
0.777594633388
80
0.794945480484
80
0.836808493482
80
0.836808493482
80
0.836808493482
80
0.777594633388
80
0.881845618579
90
0.769512992547
80
0.786052762811
80
0.794945480484
80
0.864428329691
90
0.849744875934
80
0.849744875934
80
0.814358094477
80
0.864428329691
90
0.904544271385
90
0.777594633388
80
0.849744875934
80
0.864428329691
90
0.836808493482
80
1.5684879401
160
0.786052762811
80
1.5684879401
160
0.825113109769
80
0.814358094477
80
0.825113109769
80
0.794945480484
80
0.786052762811
80
0.825113109769
80
1.6951988169
170
1.09951761712
110
0.836808493482
80
0.825113109769
80
0.777594633388
80
0.769512992547
80
0.761761636674
80
0.733399971173
70
0.754303104057
80
1.35713666006
140
1.4588891492
150
1.0357049901
100
0.786052762811
80
0.769512992547
80
0.93117436373
90
0.6799204801
70
0.664239891003
70
2.0
200
0.961834703905
100
1.74330571128
170
1.4588891492
150
0.726849522068
70
1.78117499294
180
0.669372522118
70
0.626011957506
60
1.18409073564
120
1.19810883646
120
1.44653859517
140
0.6
60
1.46268235067
150
0.654233545742
70
0.912413675981
90
1.41169361572
140
0.690882552702
70
0.726849522068
70
1.04782084474
100
0.886337865269
90
0.621537506166
60
1.6869540667
170
1.22351338414
120
1.73197778191
170
0.921642876107
90
0.903465521114
90
1.25764373833
130
1.41169361572
140
1.19810883646
120
1.46504330918
150
1.23460148671
120
1.57115943439
160
1.10970933691
110
1.01156761743
100
1.14501353806
110
0.664239891003
70
0.819214579445
80
0.862333221271
90
1.491438695
150
0.854728548761
90
1.3492903583
130
1.14501353806
110
0.664239891003
70
0.87812557478
90
1.19810883646
120
0.903465521114
90
0.93117436373
90
0.6
60
1.22788632417
120
1.46504330918
150
1.14501353806
110
0.941031865596
90
1.19810883646
120
1.05745156228
110
0.654233545742
70
1.02190647932
100
0.6799204801
70
0.793336841205
80
0.862333221271
90
1.19810883646
120
1.13286470244
110
0.644545106678
60
0.996271576441
100
0.886337865269
90
0.787165569046
80
0.994648819835
100
0.912413675981
90
1.0357049901
100
0.854728548761
90
1.27773380716
130
0.690882552702
70
0.612761858788
60
1.19181338226
120
0.630547294133
60
1.78117499294
180
0.862333221271
90
1.64927685965
160
0.696534998675
70
0.664239891003
70
0.621537506166
60
0.806025926754
80
0.630547294133
60
0.685346689583
70
0.903465521114
90
0.659195016577
70
0.894779322368
90
0.781103059873
80
0.664239891003
70
0.626011957506
60
0.659195016577
70
0.894779322368
90
0.972843915251
100
0.654233545742
70
0.630547294133
60
0.604202994491
60

In [121]:
hdf

,hours,dayofweek,visits,sumCPAVisits,conversion_rate,sqrt_visits,z_criteria,bid_adjustment,new_visits,new_cost,new_cpa_visits
0,0,0,27,1,0.037037,5.196152,-0.113163,0.951242,25.683534,24.431256,0.951242
1,0,1,34,0,0.000000,5.830952,-4.463170,0.639811,21.753575,13.918177,0.000000
2,0,2,20,0,0.000000,4.472136,-3.423095,0.714273,14.285466,10.203728,0.000000
3,0,3,14,0,0.000000,3.741657,-2.863967,0.754303,10.560243,7.965624,0.000000
4,0,4,17,0,0.000000,4.123106,-3.155938,0.733400,12.467800,9.143884,0.000000
5,0,5,30,1,0.033333,5.477226,-0.526597,0.921643,27.649286,25.482768,0.921643
6,0,6,27,1,0.037037,5.196152,-0.113163,0.951242,25.683534,24.431256,0.951242
7,1,0,18,1,0.055556,4.242641,1.485121,1.065668,19.182029,20.441679,1.065668
8,1,1,19,0,0.000000,4.358899,-3.336421,0.720479,13.689094,9.862700,0.000000
9,1,2,12,0,0.000000,3.464102,-2.651518,0.769513,9.234156,7.105803,0.000000
10,1,3,15,1,0.066667,3.872983,2.219766,1.118264,16.773958,18.757710,1.118264
11,1,4,21,2,0.095238,4.582576,5.255360,1.335592,28.047425,37.459907,2.671183
12,1,5,14,0,0.000000,3.741657,-2.863967,0.754303,10.560243,7.965624,0.000000
13,1,6,18,1,0.055556,4.242641,1.485121,1.065668,19.182029,20.441679,1.065668
14,2,0,10,0,0.000000,3.162278,-2.420494,0.786053,7.860528,6.178789,0.000000
15,2,1,11,0,0.000000,3.316625,-2.538635,0.777595,8.553541,6.651188,0.000000
16,2,2,11,0,0.000000,3.316625,-2.538635,0.777595,8.553541,6.651188,0.000000
17,2,3,10,0,0.000000,3.162278,-2.420494,0.786053,7.860528,6.178789,0.000000
18,2,4,12,1,0.083333,3.464102,3.144654,1.184479,14.213754,16.835900,1.184479
19,2,5,16,0,0.000000,4.000000,-3.061710,0.740146,11.842337,8.765060,0.000000
20,2,6,18,0,0.000000,4.242641,-3.247433,0.726850,13.083291,9.509584,0.000000
21,3,0,7,0,0.000000,2.645751,-2.025131,0.814358,5.700507,4.642254,0.000000
22,3,1,3,0,0.000000,1.732051,-1.325759,0.864428,2.593285,2.241709,0.000000
23,3,2,4,0,0.000000,2.000000,-1.530855,0.849745,3.398980,2.888265,0.000000
24,3,3,10,0,0.000000,3.162278,-2.420494,0.786053,7.860528,6.178789,0.000000
25,3,4,7,0,0.000000,2.645751,-2.025131,0.814358,5.700507,4.642254,0.000000
26,3,5,11,0,0.000000,3.316625,-2.538635,0.777595,8.553541,6.651188,0.000000
27,3,6,9,0,0.000000,3.000000,-2.296282,0.794945,7.154509,5.687445,0.000000
28,4,0,5,0,0.000000,2.236068,-1.711548,0.836808,4.184042,3.501242,0.000000
29,4,1,5,0,0.000000,2.236068,-1.711548,0.836808,4.184042,3.501242,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
137,19,5,48,2,0.041667,6.928203,0.493136,0.994649,47.743143,47.487661,1.989298
138,19,6,31,1,0.032258,5.567764,-0.655509,0.912414,28.284824,25.807460,0.912414
139,20,0,20,1,0.050000,4.472136,1.066600,1.035705,20.714100,21.453697,1.035705
140,20,1,38,1,0.026316,6.164414,-1.461244,0.854729,32.479685,27.761314,0.854729
141,20,2,24,2,0.083333,4.898979,4.447212,1.277734,30.665611,39.182488,2.555468
142,20,3,24,0,0.000000,4.898979,-3.749813,0.690883,16.581181,11.455649,0.000000
143,20,4,40,0,0.000000,6.324555,-4.840988,0.612762,24.510474,15.019084,0.000000
144,20,5,49,3,0.061224,7.000000,3.247092,1.191813,58.398856,69.600538,3.575440
145,20,6,36,0,0.000000,6.000000,-4.592564,0.630547,22.699703,14.313236,0.000000
146,21,0,27,4,0.148148,5.196152,11.479182,1.781175,48.091725,85.659778,7.124700
147,21,1,37,1,0.027027,6.082763,-1.355023,0.862333,31.906329,27.513888,0.862333
148,21,2,21,3,0.142857,4.582576,9.636854,1.649277,34.634814,57.122397,4.947831
149,21,3,23,0,0.000000,4.795832,-3.670861,0.696535,16.020305,11.158703,0.000000
150,21,4,29,0,0.000000,5.385165,-4.121953,0.664240,19.262957,12.795224,0.000000
151,21,5,38,0,0.000000,6.164414,-4.718411,0.621538,23.618425,14.679737,0.000000
152,21,6,45,1,0.022222,6.708204,-2.141513,0.806026,36.271167,29.235501,0.806026
153,22,0,36,0,0.000000,6.000000,-4.592564,0.630547,22.699703,14.313236,0.000000
154,22,1,25,0,0.000000,5.000000,-3.827137,0.685347,17.133667,11.742502,0.000000
155,22,2,32,1,0.031250,5.656854,-0.780495,0.903466,28.910897,26.119998,0.903466
156,22,3,30,0,0.000000,5.477226,-4.192418,0.659195,19.775850,13.036142,0.000000
157,22,4,33,1,0.030303,5.744563,-0.901822,0.894779,29.527718,26.420791,0.894779
158,22,5,49,1,0.020408,7.000000,-2.489630,0.781103,38.274050,29.895978,0.781103
159,22,6,29,0,0.000000,5.385165,-4.121953,0.664240,19.262957,12.795224,0.000000
160,23,0,37,0,0.000000,6.082763,-4.655913,0.626012,23.162442,14.499966,0.000000
161,23,1,30,0,0.000000,5.477226,-4.192418,0.659195,19.775850,13.036142,0.000000
162,23,2,33,1,0.030303,5.744563,-0.901822,0.894779,29.527718,26.420791,0.894779
163,23,3,25,1,0.040000,5.000000,0.188569,0.972844,24.321098,23.660632,0.972844
164,23,4,31,0,0.000000,5.567764,-4.261719,0.654234,20.281240,13.268668,0.000000
165,23,5,36,0,0.000000,6.000000,-4.592564,0.630547,22.699703,14.313236,0.000000
166,23,6,42,0,0.000000,6.480741,-4.960536,0.604203,25.376526,15.332573,0.000000

In [127]:
pd.DataFrame(schedule).to_clipboard()

In [128]:
schedule

[{'day': 0, 'hour': 0, 'value': 100},
 {'day': 1, 'hour': 0, 'value': 60},
 {'day': 2, 'hour': 0, 'value': 70},
 {'day': 3, 'hour': 0, 'value': 80},
 {'day': 4, 'hour': 0, 'value': 70},
 {'day': 5, 'hour': 0, 'value': 90},
 {'day': 6, 'hour': 0, 'value': 100},
 {'day': 0, 'hour': 1, 'value': 110},
 {'day': 1, 'hour': 1, 'value': 70},
 {'day': 2, 'hour': 1, 'value': 80},
 {'day': 3, 'hour': 1, 'value': 110},
 {'day': 4, 'hour': 1, 'value': 130},
 {'day': 5, 'hour': 1, 'value': 80},
 {'day': 6, 'hour': 1, 'value': 110},
 {'day': 0, 'hour': 2, 'value': 80},
 {'day': 1, 'hour': 2, 'value': 80},
 {'day': 2, 'hour': 2, 'value': 80},
 {'day': 3, 'hour': 2, 'value': 80},
 {'day': 4, 'hour': 2, 'value': 120},
 {'day': 5, 'hour': 2, 'value': 70},
 {'day': 6, 'hour': 2, 'value': 70},
 {'day': 0, 'hour': 3, 'value': 80},
 {'day': 1, 'hour': 3, 'value': 90},
 {'day': 2, 'hour': 3, 'value': 80},
 {'day': 3, 'hour': 3, 'value': 80},
 {'day': 4, 'hour': 3, 'value': 80},
 {'day': 5, 'hour': 3, 'value': 80},
 {'day': 6, 'hour': 3, 'value': 80},
 {'day': 0, 'hour': 4, 'value': 80},
 {'day': 1, 'hour': 4, 'value': 80},
 {'day': 2, 'hour': 4, 'value': 80},
 {'day': 3, 'hour': 4, 'value': 80},
 {'day': 4, 'hour': 4, 'value': 90},
 {'day': 5, 'hour': 4, 'value': 80},
 {'day': 6, 'hour': 4, 'value': 80},
 {'day': 0, 'hour': 5, 'value': 80},
 {'day': 1, 'hour': 5, 'value': 90},
 {'day': 3, 'hour': 5, 'value': 80},
 {'day': 4, 'hour': 5, 'value': 80},
 {'day': 5, 'hour': 5, 'value': 80},
 {'day': 6, 'hour': 5, 'value': 90},
 {'day': 0, 'hour': 6, 'value': 90},
 {'day': 1, 'hour': 6, 'value': 80},
 {'day': 2, 'hour': 6, 'value': 80},
 {'day': 3, 'hour': 6, 'value': 90},
 {'day': 4, 'hour': 6, 'value': 80},
 {'day': 5, 'hour': 6, 'value': 160},
 {'day': 6, 'hour': 6, 'value': 80},
 {'day': 0, 'hour': 7, 'value': 160},
 {'day': 1, 'hour': 7, 'value': 80},
 {'day': 2, 'hour': 7, 'value': 80},
 {'day': 3, 'hour': 7, 'value': 80},
 {'day': 4, 'hour': 7, 'value': 80},
 {'day': 5, 'hour': 7, 'value': 80},
 {'day': 6, 'hour': 7, 'value': 80},
 {'day': 0, 'hour': 8, 'value': 170},
 {'day': 1, 'hour': 8, 'value': 110},
 {'day': 2, 'hour': 8, 'value': 80},
 {'day': 3, 'hour': 8, 'value': 80},
 {'day': 4, 'hour': 8, 'value': 80},
 {'day': 5, 'hour': 8, 'value': 80},
 {'day': 6, 'hour': 8, 'value': 80},
 {'day': 0, 'hour': 9, 'value': 70},
 {'day': 1, 'hour': 9, 'value': 80},
 {'day': 2, 'hour': 9, 'value': 140},
 {'day': 3, 'hour': 9, 'value': 150},
 {'day': 4, 'hour': 9, 'value': 100},
 {'day': 5, 'hour': 9, 'value': 80},
 {'day': 6, 'hour': 9, 'value': 80},
 {'day': 0, 'hour': 10, 'value': 90},
 {'day': 1, 'hour': 10, 'value': 70},
 {'day': 2, 'hour': 10, 'value': 70},
 {'day': 3, 'hour': 10, 'value': 200},
 {'day': 4, 'hour': 10, 'value': 100},
 {'day': 5, 'hour': 10, 'value': 170},
 {'day': 6, 'hour': 10, 'value': 150},
 {'day': 0, 'hour': 11, 'value': 70},
 {'day': 1, 'hour': 11, 'value': 180},
 {'day': 2, 'hour': 11, 'value': 70},
 {'day': 3, 'hour': 11, 'value': 60},
 {'day': 4, 'hour': 11, 'value': 120},
 {'day': 5, 'hour': 11, 'value': 120},
 {'day': 6, 'hour': 11, 'value': 140},
 {'day': 0, 'hour': 12, 'value': 60},
 {'day': 1, 'hour': 12, 'value': 150},
 {'day': 2, 'hour': 12, 'value': 70},
 {'day': 3, 'hour': 12, 'value': 90},
 {'day': 4, 'hour': 12, 'value': 140},
 {'day': 5, 'hour': 12, 'value': 70},
 {'day': 6, 'hour': 12, 'value': 70},
 {'day': 0, 'hour': 13, 'value': 100},
 {'day': 1, 'hour': 13, 'value': 90},
 {'day': 2, 'hour': 13, 'value': 60},
 {'day': 3, 'hour': 13, 'value': 170},
 {'day': 4, 'hour': 13, 'value': 120},
 {'day': 5, 'hour': 13, 'value': 170},
 {'day': 6, 'hour': 13, 'value': 90},
 {'day': 0, 'hour': 14, 'value': 90},
 {'day': 1, 'hour': 14, 'value': 130},
 {'day': 2, 'hour': 14, 'value': 140},
 {'day': 3, 'hour': 14, 'value': 120},
 {'day': 4, 'hour': 14, 'value': 150},
 {'day': 5, 'hour': 14, 'value': 120},
 {'day': 6, 'hour': 14, 'value': 160},
 {'day': 0, 'hour': 15, 'value': 110},
 {'day': 1, 'hour': 15, 'value': 100},
 {'day': 2, 'hour': 15, 'value': 110},
 {'day': 3, 'hour': 15, 'value': 70},
 {'day': 4, 'hour': 15, 'value': 80},
 {'day': 5, 'hour': 15, 'value': 90},
 {'day': 6, 'hour': 15, 'value': 150},
 {'day': 0, 'hour': 16, 'value': 90},
 {'day': 1, 'hour': 16, 'value': 130},
 {'day': 2, 'hour': 16, 'value': 110},
 {'day': 3, 'hour': 16, 'value': 70},
 {'day': 4, 'hour': 16, 'value': 90},
 {'day': 5, 'hour': 16, 'value': 120},
 {'day': 6, 'hour': 16, 'value': 90},
 {'day': 0, 'hour': 17, 'value': 90},
 {'day': 1, 'hour': 17, 'value': 60},
 {'day': 2, 'hour': 17, 'value': 120},
 {'day': 3, 'hour': 17, 'value': 150},
 {'day': 4, 'hour': 17, 'value': 110},
 {'day': 5, 'hour': 17, 'value': 90},
 {'day': 6, 'hour': 17, 'value': 120},
 {'day': 0, 'hour': 18, 'value': 110},
 {'day': 1, 'hour': 18, 'value': 70},
 {'day': 2, 'hour': 18, 'value': 100},
 {'day': 3, 'hour': 18, 'value': 70},
 {'day': 4, 'hour': 18, 'value': 80},
 {'day': 5, 'hour': 18, 'value': 90},
 {'day': 6, 'hour': 18, 'value': 120},
 {'day': 0, 'hour': 19, 'value': 110},
 {'day': 1, 'hour': 19, 'value': 60},
 {'day': 2, 'hour': 19, 'value': 100},
 {'day': 3, 'hour': 19, 'value': 90},
 {'day': 4, 'hour': 19, 'value': 80},
 {'day': 5, 'hour': 19, 'value': 100},
 {'day': 6, 'hour': 19, 'value': 90},
 {'day': 0, 'hour': 20, 'value': 100},
 {'day': 1, 'hour': 20, 'value': 90},
 {'day': 2, 'hour': 20, 'value': 130},
 {'day': 3, 'hour': 20, 'value': 70},
 {'day': 4, 'hour': 20, 'value': 60},
 {'day': 5, 'hour': 20, 'value': 120},
 {'day': 6, 'hour': 20, 'value': 60},
 {'day': 0, 'hour': 21, 'value': 180},
 {'day': 1, 'hour': 21, 'value': 90},
 {'day': 2, 'hour': 21, 'value': 160},
 {'day': 3, 'hour': 21, 'value': 70},
 {'day': 4, 'hour': 21, 'value': 70},
 {'day': 5, 'hour': 21, 'value': 60},
 {'day': 6, 'hour': 21, 'value': 80},
 {'day': 0, 'hour': 22, 'value': 60},
 {'day': 1, 'hour': 22, 'value': 70},
 {'day': 2, 'hour': 22, 'value': 90},
 {'day': 3, 'hour': 22, 'value': 70},
 {'day': 4, 'hour': 22, 'value': 90},
 {'day': 5, 'hour': 22, 'value': 80},
 {'day': 6, 'hour': 22, 'value': 70},
 {'day': 0, 'hour': 23, 'value': 60},
 {'day': 1, 'hour': 23, 'value': 70},
 {'day': 2, 'hour': 23, 'value': 90},
 {'day': 3, 'hour': 23, 'value': 100},
 {'day': 4, 'hour': 23, 'value': 70},
 {'day': 5, 'hour': 23, 'value': 60},
 {'day': 6, 'hour': 23, 'value': 60}]